# Generated by Django 4.1.5 on 2023-12-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
                ('src', models.FileField(upload_to='songs/')),
            ],
        ),
    ]
